import { PrismaClient } from '@prisma/client';

const prisma = new PrismaClient();

const seedData = [
  // Wine & Dine Category (15+ items)
  {
    title: 'Eat. Stay. Love.',
    description: 'An all-in-one Experience at Fratelli Vineyards awaits when you book a flight to Pune',
    imageUrl: 'https://images.unsplash.com/photo-1586370434639-0fe43b2d32d6?w=400&h=300&fit=crop',
    destination: 'Pune',
    category: 'Wine & Dine',
    price: 299.99,
    duration: '3 days',
    featured: true,
  },
  {
    title: 'Sun Set Savour',
    description: 'Enjoy an exclusive Experience at Sula Vineyards when you book a flight to Nashik',
    imageUrl: 'https://images.unsplash.com/photo-1547036967-23d11aacaee0?w=400&h=300&fit=crop',
    destination: 'Nashik',
    category: 'Wine & Dine',
    price: 249.99,
    duration: '2 days',
    featured: true,
  },
  {
    title: 'Michelin Star Experience',
    description: 'Indulge in exquisite fine dining at award-winning restaurants in Mumbai',
    imageUrl: 'https://images.unsplash.com/photo-1559339352-11d035aa65de?w=400&h=300&fit=crop',
    destination: 'Mumbai',
    category: 'Wine & Dine',
    price: 450.00,
    duration: '1 day',
    featured: false,
  },
  {
    title: 'Kerala Spice Plantation Tour',
    description: 'Discover authentic spices and traditional cooking methods in Thekkady',
    imageUrl: 'https://images.unsplash.com/photo-1596040033229-a9821ebd058d?w=400&h=300&fit=crop',
    destination: 'Kerala',
    category: 'Wine & Dine',
    price: 180.00,
    duration: '2 days',
    featured: false,
  },
  {
    title: 'Rajasthani Royal Feast',
    description: 'Experience royal dining in heritage palaces with traditional Rajasthani cuisine',
    imageUrl: 'https://images.unsplash.com/photo-1585937421612-70a008356fbe?w=400&h=300&fit=crop',
    destination: 'Jaipur',
    category: 'Wine & Dine',
    price: 320.00,
    duration: '1 day',
    featured: false,
  },
  {
    title: 'Goan Beach Shack Crawl',
    description: 'Taste authentic Goan seafood at the best beach shacks along the coast',
    imageUrl: 'https://images.unsplash.com/photo-1555939594-58d7cb561ad1?w=400&h=300&fit=crop',
    destination: 'Goa',
    category: 'Wine & Dine',
    price: 125.00,
    duration: '1 day',
    featured: false,
  },
  {
    title: 'Bengali Sweet Trail',
    description: 'Explore Kolkata\'s famous sweet shops and traditional Bengali delicacies',
    imageUrl: 'https://images.unsplash.com/photo-1578985545062-69928b1d9587?w=400&h=300&fit=crop',
    destination: 'Kolkata',
    category: 'Wine & Dine',
    price: 89.99,
    duration: '1 day',
    featured: false,
  },
  {
    title: 'Punjabi Dhaba Experience',
    description: 'Authentic Punjabi cuisine at traditional roadside dhabas in Amritsar',
    imageUrl: 'https://images.unsplash.com/photo-1565299624946-b28f40a0ca4b?w=400&h=300&fit=crop',
    destination: 'Amritsar',
    category: 'Wine & Dine',
    price: 95.00,
    duration: '1 day',
    featured: false,
  },
  {
    title: 'South Indian Culinary Journey',
    description: 'Master the art of South Indian cooking with expert chefs in Chennai',
    imageUrl: 'https://images.unsplash.com/photo-1567229569827-fde6edec4344?w=400&h=300&fit=crop',
    destination: 'Chennai',
    category: 'Wine & Dine',
    price: 210.00,
    duration: '2 days',
    featured: false,
  },
  {
    title: 'Hyderabadi Biryani Trail',
    description: 'Discover the secrets of authentic Hyderabadi biryani at iconic eateries',
    imageUrl: 'https://images.unsplash.com/photo-1563379091339-03246963d96c?w=400&h=300&fit=crop',
    destination: 'Hyderabad',
    category: 'Wine & Dine',
    price: 135.00,
    duration: '1 day',
    featured: false,
  },
  {
    title: 'Himalayan Organic Farm Dining',
    description: 'Farm-to-table experience in the pristine valleys of Himachal Pradesh',
    imageUrl: 'https://images.unsplash.com/photo-1574323347407-f5e1ad6d020b?w=400&h=300&fit=crop',
    destination: 'Manali',
    category: 'Wine & Dine',
    price: 275.00,
    duration: '2 days',
    featured: false,
  },
  {
    title: 'Udaipur Lake Palace Dinner',
    description: 'Romantic dining experience at the floating palace on Lake Pichola',
    imageUrl: 'https://images.unsplash.com/photo-1582555172866-f73bb12a2ab3?w=400&h=300&fit=crop',
    destination: 'Udaipur',
    category: 'Wine & Dine',
    price: 550.00,
    duration: '1 day',
    featured: true,
  },
  {
    title: 'Gujarat Thali Experience',
    description: 'Unlimited traditional Gujarati thali with authentic flavors in Ahmedabad',
    imageUrl: 'https://images.unsplash.com/photo-1565299507177-b0ac66763828?w=400&h=300&fit=crop',
    destination: 'Ahmedabad',
    category: 'Wine & Dine',
    price: 75.00,
    duration: '1 day',
    featured: false,
  },
  {
    title: 'Konkani Coastal Cuisine',
    description: 'Fresh seafood and coconut-based dishes in scenic Mangalore',
    imageUrl: 'https://images.unsplash.com/photo-1615141982883-c7ad0e69fd62?w=400&h=300&fit=crop',
    destination: 'Mangalore',
    category: 'Wine & Dine',
    price: 165.00,
    duration: '1 day',
    featured: false,
  },
  {
    title: 'Assamese Tea Garden Lunch',
    description: 'Traditional Assamese cuisine amidst lush tea gardens in Dibrugarh',
    imageUrl: 'https://images.unsplash.com/photo-1597318499820-902de2168885?w=400&h=300&fit=crop',
    destination: 'Dibrugarh',
    category: 'Wine & Dine',
    price: 145.00,
    duration: '1 day',
    featured: false,
  },

  // Cultural Category (15+ items)
  {
    title: 'Festivals From India',
    description: 'Explore arts and culture festivals across India.',
    imageUrl: 'https://images.unsplash.com/photo-1578662996442-48f60103fc96?w=400&h=300&fit=crop',
    destination: 'India',
    category: 'Cultural',
    price: 199.99,
    duration: '5 days',
    featured: true,
  },
  {
    title: 'Holi Festival in Mathura',
    description: 'Experience the most vibrant Holi celebration at Krishna\'s birthplace',
    imageUrl: 'https://images.unsplash.com/photo-1584464491033-06628f3a6b7b?w=400&h=300&fit=crop',
    destination: 'Mathura',
    category: 'Cultural',
    price: 150.00,
    duration: '2 days',
    featured: true,
  },
  {
    title: 'Pushkar Camel Fair',
    description: 'Witness the spectacular camel fair and cultural performances in Rajasthan',
    imageUrl: 'https://images.unsplash.com/photo-1564507592333-c60657eea523?w=400&h=300&fit=crop',
    destination: 'Pushkar',
    category: 'Cultural',
    price: 225.00,
    duration: '3 days',
    featured: false,
  },
  {
    title: 'Kochi Kathakali Performance',
    description: 'Traditional Kathakali dance drama in the cultural heart of Kerala',
    imageUrl: 'https://images.unsplash.com/photo-1587474260584-136574528ed5?w=400&h=300&fit=crop',
    destination: 'Kochi',
    category: 'Cultural',
    price: 89.99,
    duration: '1 day',
    featured: false,
  },
  {
    title: 'Durga Puja in Kolkata',
    description: 'Immerse in the grandest festival of Bengal with pandal hopping',
    imageUrl: 'https://images.unsplash.com/photo-1571115764595-644a1f56a55c?w=400&h=300&fit=crop',
    destination: 'Kolkata',
    category: 'Cultural',
    price: 175.00,
    duration: '4 days',
    featured: true,
  },
  {
    title: 'Varanasi Ganga Aarti',
    description: 'Witness the spiritual evening aarti ceremony on the ghats of Varanasi',
    imageUrl: 'https://images.unsplash.com/photo-1561361513-2d000a50f0dc?w=400&h=300&fit=crop',
    destination: 'Varanasi',
    category: 'Cultural',
    price: 125.00,
    duration: '2 days',
    featured: false,
  },
  {
    title: 'Bharatanatyam Workshop',
    description: 'Learn classical Indian dance from master performers in Chennai',
    imageUrl: 'https://images.unsplash.com/photo-1594736797933-d0401ba2fe65?w=400&h=300&fit=crop',
    destination: 'Chennai',
    category: 'Cultural',
    price: 195.00,
    duration: '3 days',
    featured: false,
  },
  {
    title: 'Odissi Dance Heritage',
    description: 'Explore the ancient dance form of Odissi in temple city Bhubaneswar',
    imageUrl: 'https://images.unsplash.com/photo-1518611012118-696072aa579a?w=400&h=300&fit=crop',
    destination: 'Bhubaneswar',
    category: 'Cultural',
    price: 160.00,
    duration: '2 days',
    featured: false,
  },
  {
    title: 'Rajasthani Folk Music Night',
    description: 'Enchanting folk music performances under the desert stars in Jaisalmer',
    imageUrl: 'https://images.unsplash.com/photo-1509316975850-ff9c5deb0cd9?w=400&h=300&fit=crop',
    destination: 'Jaisalmer',
    category: 'Cultural',
    price: 185.00,
    duration: '1 day',
    featured: false,
  },
  {
    title: 'Madhubani Art Workshop',
    description: 'Learn traditional Madhubani painting from village artists in Bihar',
    imageUrl: 'https://images.unsplash.com/photo-1578321272176-b7bbc0679853?w=400&h=300&fit=crop',
    destination: 'Bihar',
    category: 'Cultural',
    price: 110.00,
    duration: '2 days',
    featured: false,
  },
  {
    title: 'Warli Tribal Art Experience',
    description: 'Discover ancient Warli art traditions with tribal communities in Maharashtra',
    imageUrl: 'https://images.unsplash.com/photo-1598300042247-d088f8ab3a91?w=400&h=300&fit=crop',
    destination: 'Maharashtra',
    category: 'Cultural',
    price: 135.00,
    duration: '2 days',
    featured: false,
  },
  {
    title: 'Theyyam Ritual Performance',
    description: 'Witness the mystical Theyyam ritual performances in North Kerala',
    imageUrl: 'https://images.unsplash.com/photo-1505455184862-554165e5f6ba?w=400&h=300&fit=crop',
    destination: 'Kannur',
    category: 'Cultural',
    price: 145.00,
    duration: '1 day',
    featured: false,
  },
  {
    title: 'Sufi Music in Ajmer',
    description: 'Soul-stirring Sufi music sessions at the Ajmer Sharif Dargah',
    imageUrl: 'https://images.unsplash.com/photo-1493225457124-a3eb161ffa5f?w=400&h=300&fit=crop',
    destination: 'Ajmer',
    category: 'Cultural',
    price: 95.00,
    duration: '1 day',
    featured: false,
  },
  {
    title: 'Manipuri Classical Dance',
    description: 'Experience graceful Manipuri dance performances in Imphal',
    imageUrl: 'https://images.unsplash.com/photo-1594996797-06a5ba5b2b1f?w=400&h=300&fit=crop',
    destination: 'Imphal',
    category: 'Cultural',
    price: 155.00,
    duration: '2 days',
    featured: false,
  },
  {
    title: 'Hornbill Festival',
    description: 'Celebrate Nagaland\'s rich cultural heritage at the Festival of Festivals',
    imageUrl: 'https://images.unsplash.com/photo-1445019980597-93fa8acb246c?w=400&h=300&fit=crop',
    destination: 'Kohima',
    category: 'Cultural',
    price: 285.00,
    duration: '4 days',
    featured: true,
  },

  // Adventure Category (15+ items)
  {
    title: 'Travel wanderlust',
    description: 'Travel to your next destination based on how you feel and what you like.',
    imageUrl: 'https://images.unsplash.com/photo-1488646953014-85cb44e25828?w=400&h=300&fit=crop',
    destination: 'Multiple',
    category: 'Adventure',
    price: 599.99,
    duration: '7 days',
    featured: true,
  },
  {
    title: 'Himalayan Adventure',
    description: 'Trek through the majestic Himalayas with professional guides.',
    imageUrl: 'https://images.unsplash.com/photo-1544735716-392fe2489ffa?w=400&h=300&fit=crop',
    destination: 'Himachal Pradesh',
    category: 'Adventure',
    price: 899.99,
    duration: '8 days',
    featured: false,
  },
  {
    title: 'Leh Ladakh Bike Expedition',
    description: 'Epic motorcycle journey through the high-altitude desert landscapes',
    imageUrl: 'https://images.unsplash.com/photo-1609655981355-e4b7fcac2e78?w=400&h=300&fit=crop',
    destination: 'Leh Ladakh',
    category: 'Adventure',
    price: 1299.99,
    duration: '12 days',
    featured: true,
  },
  {
    title: 'River Rafting in Rishikesh',
    description: 'Thrilling white water rafting on the sacred Ganges river',
    imageUrl: 'https://images.unsplash.com/photo-1580687198291-11668c0c4012?w=400&h=300&fit=crop',
    destination: 'Rishikesh',
    category: 'Adventure',
    price: 185.00,
    duration: '1 day',
    featured: false,
  },
  {
    title: 'Paragliding in Bir Billing',
    description: 'Soar through the skies at one of the world\'s best paragliding sites',
    imageUrl: 'https://images.unsplash.com/photo-1540979388789-6cee28a1cdc9?w=400&h=300&fit=crop',
    destination: 'Bir',
    category: 'Adventure',
    price: 225.00,
    duration: '2 days',
    featured: false,
  },
  {
    title: 'Scuba Diving in Andamans',
    description: 'Explore vibrant coral reefs and marine life in crystal clear waters',
    imageUrl: 'https://images.unsplash.com/photo-1583212292454-1fe6229603b7?w=400&h=300&fit=crop',
    destination: 'Andaman Islands',
    category: 'Adventure',
    price: 450.00,
    duration: '3 days',
    featured: false,
  },
  {
    title: 'Rock Climbing in Hampi',
    description: 'Challenge yourself on ancient boulder formations in the historic ruins',
    imageUrl: 'https://images.unsplash.com/photo-1522163182402-834f871fd851?w=400&h=300&fit=crop',
    destination: 'Hampi',
    category: 'Adventure',
    price: 195.00,
    duration: '2 days',
    featured: false,
  },
  {
    title: 'Desert Safari in Thar',
    description: 'Camel safari and camping under the stars in Rajasthan\'s golden desert',
    imageUrl: 'https://images.unsplash.com/photo-1584200190441-6b43e24dbf04?w=400&h=300&fit=crop',
    destination: 'Jaisalmer',
    category: 'Adventure',
    price: 275.00,
    duration: '3 days',
    featured: false,
  },
  {
    title: 'Bungee Jumping in Goa',
    description: 'Take the ultimate leap of faith at India\'s highest bungee jump',
    imageUrl: 'https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?w=400&h=300&fit=crop',
    destination: 'Goa',
    category: 'Adventure',
    price: 145.00,
    duration: '1 day',
    featured: false,
  },
  {
    title: 'Skiing in Gulmarg',
    description: 'Experience world-class skiing on pristine Himalayan slopes',
    imageUrl: 'https://images.unsplash.com/photo-1578632292335-89a6024c4383?w=400&h=300&fit=crop',
    destination: 'Gulmarg',
    category: 'Adventure',
    price: 395.00,
    duration: '4 days',
    featured: false,
  },
  {
    title: 'Hot Air Balloon over Jaipur',
    description: 'Aerial views of the Pink City from a colorful hot air balloon',
    imageUrl: 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=400&h=300&fit=crop',
    destination: 'Jaipur',
    category: 'Adventure',
    price: 185.00,
    duration: '1 day',
    featured: false,
  },
  {
    title: 'Canyoning in Dandeli',
    description: 'Navigate waterfalls and gorges in Karnataka\'s adventure capital',
    imageUrl: 'https://images.unsplash.com/photo-1624798584133-eaf5e52bb5bf?w=400&h=300&fit=crop',
    destination: 'Dandeli',
    category: 'Adventure',
    price: 165.00,
    duration: '2 days',
    featured: false,
  },
  {
    title: 'Ice Climbing in Manali',
    description: 'Conquer frozen waterfalls in the winter wonderland of Himachal',
    imageUrl: 'https://images.unsplash.com/photo-1578849278619-e73505e9610f?w=400&h=300&fit=crop',
    destination: 'Manali',
    category: 'Adventure',
    price: 325.00,
    duration: '3 days',
    featured: false,
  },
  {
    title: 'Zipline Adventure in Munnar',
    description: 'Fly through tea plantations on the longest zipline in South India',
    imageUrl: 'https://images.unsplash.com/photo-1499696010180-025ef6e1a8f9?w=400&h=300&fit=crop',
    destination: 'Munnar',
    category: 'Adventure',
    price: 115.00,
    duration: '1 day',
    featured: false,
  },
  {
    title: 'Surfing in Varkala',
    description: 'Ride the waves at Kerala\'s premier surfing destination',
    imageUrl: 'https://images.unsplash.com/photo-1502680390469-be75c86b636f?w=400&h=300&fit=crop',
    destination: 'Varkala',
    category: 'Adventure',
    price: 135.00,
    duration: '2 days',
    featured: false,
  },

  // Nature Category (15+ items)
  {
    title: 'Kerala Backwaters',
    description: 'Experience the serene backwaters of Kerala with traditional houseboat stays.',
    imageUrl: 'https://images.unsplash.com/photo-1575130350197-29c84c52e12b?w=400&h=300&fit=crop',
    destination: 'Kerala',
    category: 'Nature',
    price: 449.99,
    duration: '4 days',
    featured: false,
  },
  {
    title: 'Sundarbans Mangrove Safari',
    description: 'Spot Royal Bengal tigers in the world\'s largest mangrove forest',
    imageUrl: 'https://images.unsplash.com/photo-1612817159949-195b6eb9e31a?w=400&h=300&fit=crop',
    destination: 'West Bengal',
    category: 'Nature',
    price: 385.00,
    duration: '3 days',
    featured: true,
  },
  {
    title: 'Valley of Flowers Trek',
    description: 'Witness a UNESCO World Heritage site blooming with alpine flowers',
    imageUrl: 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=400&h=300&fit=crop',
    destination: 'Uttarakhand',
    category: 'Nature',
    price: 495.00,
    duration: '6 days',
    featured: true,
  },
  {
    title: 'Coorg Coffee Plantation Walk',
    description: 'Explore aromatic coffee estates in the Scotland of India',
    imageUrl: 'https://images.unsplash.com/photo-1587593810167-a84920ea0781?w=400&h=300&fit=crop',
    destination: 'Coorg',
    category: 'Nature',
    price: 225.00,
    duration: '2 days',
    featured: false,
  },
  {
    title: 'Jim Corbett Wildlife Safari',
    description: 'Track tigers and elephants in India\'s first national park',
    imageUrl: 'https://images.unsplash.com/photo-1596040033229-a9821ebd058d?w=400&h=300&fit=crop',
    destination: 'Uttarakhand',
    category: 'Nature',
    price: 295.00,
    duration: '3 days',
    featured: false,
  },
  {
    title: 'Rann of Kutch Salt Desert',
    description: 'Witness the vast white salt desert under the full moon',
    imageUrl: 'https://images.unsplash.com/photo-1571115764595-644a1f56a55c?w=400&h=300&fit=crop',
    destination: 'Gujarat',
    category: 'Nature',
    price: 185.00,
    duration: '2 days',
    featured: false,
  },
  {
    title: 'Silent Valley Rainforest',
    description: 'Explore pristine tropical rainforest with endemic species',
    imageUrl: 'https://images.unsplash.com/photo-1441974231531-c6227db76b6e?w=400&h=300&fit=crop',
    destination: 'Kerala',
    category: 'Nature',
    price: 265.00,
    duration: '3 days',
    featured: false,
  },
  {
    title: 'Nanda Devi Biosphere',
    description: 'High-altitude biodiversity in the heart of the Himalayas',
    imageUrl: 'https://images.unsplash.com/photo-1464822759844-d150ad6cca28?w=400&h=300&fit=crop',
    destination: 'Uttarakhand',
    category: 'Nature',
    price: 545.00,
    duration: '7 days',
    featured: false,
  },
  {
    title: 'Bandhavgarh Tiger Reserve',
    description: 'Highest density of tigers in India with excellent sighting opportunities',
    imageUrl: 'https://images.unsplash.com/photo-1605728559077-c8d7d4db6b10?w=400&h=300&fit=crop',
    destination: 'Madhya Pradesh',
    category: 'Nature',
    price: 335.00,
    duration: '3 days',
    featured: false,
  },
  {
    title: 'Nilgiri Mountain Railway',
    description: 'Scenic toy train journey through the Blue Mountains',
    imageUrl: 'https://images.unsplash.com/photo-1544531585-9847b68c8c86?w=400&h=300&fit=crop',
    destination: 'Tamil Nadu',
    category: 'Nature',
    price: 155.00,
    duration: '2 days',
    featured: false,
  },
  {
    title: 'Kaziranga Rhino Safari',
    description: 'Home to two-thirds of the world\'s great one-horned rhinoceros',
    imageUrl: 'https://images.unsplash.com/photo-1534177616072-ef7dc120449d?w=400&h=300&fit=crop',
    destination: 'Assam',
    category: 'Nature',
    price: 365.00,
    duration: '3 days',
    featured: false,
  },
  {
    title: 'Periyar Wildlife Sanctuary',
    description: 'Boat safari on Periyar Lake surrounded by tropical forests',
    imageUrl: 'https://images.unsplash.com/photo-1593693411515-c20261bcad6b?w=400&h=300&fit=crop',
    destination: 'Kerala',
    category: 'Nature',
    price: 215.00,
    duration: '2 days',
    featured: false,
  },
  {
    title: 'Great Himalayan National Park',
    description: 'UNESCO World Heritage site with pristine alpine ecosystems',
    imageUrl: 'https://images.unsplash.com/photo-1464822759844-d150ad6cca28?w=400&h=300&fit=crop',
    destination: 'Himachal Pradesh',
    category: 'Nature',
    price: 425.00,
    duration: '5 days',
    featured: false,
  },
  {
    title: 'Bhitarkanika Mangroves',
    description: 'Spot saltwater crocodiles and diverse bird species in Odisha',
    imageUrl: 'https://images.unsplash.com/photo-1568393691622-c704d2bb4059?w=400&h=300&fit=crop',
    destination: 'Odisha',
    category: 'Nature',
    price: 195.00,
    duration: '2 days',
    featured: false,
  },
  {
    title: 'Spiti Valley Wilderness',
    description: 'Cold desert landscape with snow leopards and rare wildlife',
    imageUrl: 'https://images.unsplash.com/photo-1586370434639-0fe43b2d32d6?w=400&h=300&fit=crop',
    destination: 'Himachal Pradesh',
    category: 'Nature',
    price: 695.00,
    duration: '8 days',
    featured: true,
  },

  // Heritage Category (15+ items)
  {
    title: 'Rajasthan Heritage',
    description: 'Discover the royal heritage of Rajasthan with palace tours and cultural experiences.',
    imageUrl: 'https://images.unsplash.com/photo-1580800964973-ef9d7d5ac96a?w=400&h=300&fit=crop',
    destination: 'Rajasthan',
    category: 'Heritage',
    price: 699.99,
    duration: '6 days',
    featured: false,
  },
  {
    title: 'Delhi Historical Walk',
    description: 'Walk through centuries of history in India\'s capital city.',
    imageUrl: 'https://images.unsplash.com/photo-1601293793451-5fa8fada0e00?w=400&h=300&fit=crop',
    destination: 'Delhi',
    category: 'Heritage',
    price: 99.99,
    duration: '1 day',
    featured: false,
  },
  {
    title: 'Taj Mahal Sunrise Experience',
    description: 'Witness the ethereal beauty of the Taj Mahal at sunrise with skip-the-line access',
    imageUrl: 'https://images.unsplash.com/photo-1564507592333-c60657eea523?w=400&h=300&fit=crop',
    destination: 'Agra',
    category: 'Heritage',
    price: 125.00,
    duration: '1 day',
    featured: true,
  },
  {
    title: 'Hampi Ruins Exploration',
    description: 'Explore the magnificent ruins of the Vijayanagara Empire',
    imageUrl: 'https://images.unsplash.com/photo-1598300042247-d088f8ab3a91?w=400&h=300&fit=crop',
    destination: 'Karnataka',
    category: 'Heritage',
    price: 185.00,
    duration: '2 days',
    featured: false,
  },
  {
    title: 'Khajuraho Temple Complex',
    description: 'Marvel at the intricate carvings of the UNESCO World Heritage temples',
    imageUrl: 'https://images.unsplash.com/photo-1578321272176-b7bbc0679853?w=400&h=300&fit=crop',
    destination: 'Madhya Pradesh',
    category: 'Heritage',
    price: 145.00,
    duration: '2 days',
    featured: false,
  },
  {
    title: 'Ajanta and Ellora Caves',
    description: 'Journey through ancient Buddhist, Hindu, and Jain rock-cut caves',
    imageUrl: 'https://images.unsplash.com/photo-1505455184862-554165e5f6ba?w=400&h=300&fit=crop',
    destination: 'Maharashtra',
    category: 'Heritage',
    price: 165.00,
    duration: '2 days',
    featured: false,
  },
  {
    title: 'Mysore Palace Royal Tour',
    description: 'Explore the opulent Mysore Palace with its Indo-Saracenic architecture',
    imageUrl: 'https://images.unsplash.com/photo-1582555172866-f73bb12a2ab3?w=400&h=300&fit=crop',
    destination: 'Mysore',
    category: 'Heritage',
    price: 95.00,
    duration: '1 day',
    featured: false,
  },
  {
    title: 'Fatehpur Sikri Ghost City',
    description: 'Walk through Akbar\'s abandoned red sandstone city near Agra',
    imageUrl: 'https://images.unsplash.com/photo-1509316975850-ff9c5deb0cd9?w=400&h=300&fit=crop',
    destination: 'Uttar Pradesh',
    category: 'Heritage',
    price: 85.00,
    duration: '1 day',
    featured: false,
  },
  {
    title: 'Konark Sun Temple',
    description: 'Discover the architectural marvel dedicated to the Sun God in Odisha',
    imageUrl: 'https://images.unsplash.com/photo-1518611012118-696072aa579a?w=400&h=300&fit=crop',
    destination: 'Odisha',
    category: 'Heritage',
    price: 115.00,
    duration: '1 day',
    featured: false,
  },
  {
    title: 'Mahabalipuram Shore Temples',
    description: 'Ancient rock-cut temples overlooking the Bay of Bengal',
    imageUrl: 'https://images.unsplash.com/photo-1571115764595-644a1f56a55c?w=400&h=300&fit=crop',
    destination: 'Tamil Nadu',
    category: 'Heritage',
    price: 105.00,
    duration: '1 day',
    featured: false,
  },
  {
    title: 'Amber Fort and Palace',
    description: 'Elephant ride to the hilltop fortress with stunning architecture',
    imageUrl: 'https://images.unsplash.com/photo-1561361513-2d000a50f0dc?w=400&h=300&fit=crop',
    destination: 'Jaipur',
    category: 'Heritage',
    price: 135.00,
    duration: '1 day',
    featured: false,
  },
  {
    title: 'Sanchi Stupa Buddhist Heritage',
    description: 'Explore the ancient Buddhist monument dating back to 3rd century BCE',
    imageUrl: 'https://images.unsplash.com/photo-1587474260584-136574528ed5?w=400&h=300&fit=crop',
    destination: 'Madhya Pradesh',
    category: 'Heritage',
    price: 125.00,
    duration: '1 day',
    featured: false,
  },
  {
    title: 'Chola Dynasty Temples',
    description: 'Visit the living Chola temples of Tamil Nadu showcasing Dravidian architecture',
    imageUrl: 'https://images.unsplash.com/photo-1594736797933-d0401ba2fe65?w=400&h=300&fit=crop',
    destination: 'Tamil Nadu',
    category: 'Heritage',
    price: 155.00,
    duration: '2 days',
    featured: false,
  },
  {
    title: 'Rani ki Vav Stepwell',
    description: 'Descend into the intricately carved stepwell in Gujarat',
    imageUrl: 'https://images.unsplash.com/photo-1493225457124-a3eb161ffa5f?w=400&h=300&fit=crop',
    destination: 'Gujarat',
    category: 'Heritage',
    price: 75.00,
    duration: '1 day',
    featured: false,
  },
  {
    title: 'Victoria Memorial Heritage Walk',
    description: 'Colonial architecture tour in the City of Joy',
    imageUrl: 'https://images.unsplash.com/photo-1445019980597-93fa8acb246c?w=400&h=300&fit=crop',
    destination: 'Kolkata',
    category: 'Heritage',
    price: 65.00,
    duration: '1 day',
    featured: false,
  },

  // Beach Category (15+ items)
  {
    title: 'Goa Beach Paradise',
    description: 'Relax on pristine beaches with water sports and vibrant nightlife.',
    imageUrl: 'https://images.unsplash.com/photo-1559827260-dc66d52bef19?w=400&h=300&fit=crop',
    destination: 'Goa',
    category: 'Beach',
    price: 349.99,
    duration: '4 days',
    featured: false,
  },
  {
    title: 'Andaman Coral Beach Diving',
    description: 'Pristine coral reefs and crystal-clear waters in the Andaman Sea',
    imageUrl: 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=400&h=300&fit=crop',
    destination: 'Andaman Islands',
    category: 'Beach',
    price: 525.00,
    duration: '5 days',
    featured: true,
  },
  {
    title: 'Kovalam Beach Ayurveda Retreat',
    description: 'Traditional Ayurvedic treatments by the crescent-shaped beaches',
    imageUrl: 'https://images.unsplash.com/photo-1540979388789-6cee28a1cdc9?w=400&h=300&fit=crop',
    destination: 'Kerala',
    category: 'Beach',
    price: 395.00,
    duration: '4 days',
    featured: false,
  },
  {
    title: 'Gokarna Hippie Beach Vibes',
    description: 'Laid-back beach town with pristine shores and cliff-top views',
    imageUrl: 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=400&h=300&fit=crop',
    destination: 'Karnataka',
    category: 'Beach',
    price: 225.00,
    duration: '3 days',
    featured: false,
  },
  {
    title: 'Puri Golden Beach Festival',
    description: 'Golden sands with cultural festivals and the famous Jagannath Temple',
    imageUrl: 'https://images.unsplash.com/photo-1471919743851-c4df8b6ee105?w=400&h=300&fit=crop',
    destination: 'Odisha',
    category: 'Beach',
    price: 185.00,
    duration: '2 days',
    featured: false,
  },
  {
    title: 'Varkala Cliff Beach Yoga',
    description: 'Yoga sessions on dramatic cliffs overlooking the Arabian Sea',
    imageUrl: 'https://images.unsplash.com/photo-1499696010180-025ef6e1a8f9?w=400&h=300&fit=crop',
    destination: 'Kerala',
    category: 'Beach',
    price: 275.00,
    duration: '3 days',
    featured: false,
  },
  {
    title: 'Pondicherry French Beach Culture',
    description: 'Colonial charm meets pristine beaches in the French Quarter',
    imageUrl: 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=400&h=300&fit=crop',
    destination: 'Pondicherry',
    category: 'Beach',
    price: 245.00,
    duration: '3 days',
    featured: false,
  },
  {
    title: 'Tarkarli Scuba Adventures',
    description: 'Crystal clear waters perfect for water sports in Maharashtra',
    imageUrl: 'https://images.unsplash.com/photo-1583212292454-1fe6229603b7?w=400&h=300&fit=crop',
    destination: 'Maharashtra',
    category: 'Beach',
    price: 195.00,
    duration: '2 days',
    featured: false,
  },
  {
    title: 'Dhanushkodi Ghost Beach',
    description: 'Mystical beach town at the tip of India with historical significance',
    imageUrl: 'https://images.unsplash.com/photo-1441974231531-c6227db76b6e?w=400&h=300&fit=crop',
    destination: 'Tamil Nadu',
    category: 'Beach',
    price: 165.00,
    duration: '2 days',
    featured: false,
  },
  {
    title: 'Marari Beach Fishing Village',
    description: 'Traditional fishing village with untouched golden beaches',
    imageUrl: 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=400&h=300&fit=crop',
    destination: 'Kerala',
    category: 'Beach',
    price: 285.00,
    duration: '3 days',
    featured: false,
  },
  {
    title: 'Chandipur Vanishing Beach',
    description: 'Unique beach where the sea disappears during low tide',
    imageUrl: 'https://images.unsplash.com/photo-1471919743851-c4df8b6ee105?w=400&h=300&fit=crop',
    destination: 'Odisha',
    category: 'Beach',
    price: 145.00,
    duration: '2 days',
    featured: false,
  },
  {
    title: 'Agatti Island Lagoon',
    description: 'Pristine coral lagoons and water sports in Lakshadweep',
    imageUrl: 'https://images.unsplash.com/photo-1502680390469-be75c86b636f?w=400&h=300&fit=crop',
    destination: 'Lakshadweep',
    category: 'Beach',
    price: 695.00,
    duration: '5 days',
    featured: true,
  },
  {
    title: 'Murudeshwar Beach Temple',
    description: 'Beach temple with the world\'s second-tallest Shiva statue',
    imageUrl: 'https://images.unsplash.com/photo-1518611012118-696072aa579a?w=400&h=300&fit=crop',
    destination: 'Karnataka',
    category: 'Beach',
    price: 155.00,
    duration: '2 days',
    featured: false,
  },
  {
    title: 'Digha Sea Beach Resort',
    description: 'Popular beach destination in West Bengal with coastal activities',
    imageUrl: 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=400&h=300&fit=crop',
    destination: 'West Bengal',
    category: 'Beach',
    price: 175.00,
    duration: '2 days',
    featured: false,
  },
  {
    title: 'Rushikonda Beach Sports',
    description: 'Golden beach in Vizag perfect for water sports and beach volleyball',
    imageUrl: 'https://images.unsplash.com/photo-1499696010180-025ef6e1a8f9?w=400&h=300&fit=crop',
    destination: 'Andhra Pradesh',
    category: 'Beach',
    price: 135.00,
    duration: '2 days',
    featured: false,
  },

  // Food Category (15+ items)
  {
    title: 'Mumbai Street Food Tour',
    description: 'Explore the bustling streets of Mumbai with local food guides.',
    imageUrl: 'https://images.unsplash.com/photo-1567129937968-cdad8f07e2f8?w=400&h=300&fit=crop',
    destination: 'Mumbai',
    category: 'Food',
    price: 149.99,
    duration: '1 day',
    featured: false,
  },
  {
    title: 'Delhi Chandni Chowk Food Walk',
    description: 'Navigate the narrow lanes of Old Delhi sampling traditional delicacies',
    imageUrl: 'https://images.unsplash.com/photo-1504674900247-0877df9cc836?w=400&h=300&fit=crop',
    destination: 'Delhi',
    category: 'Food',
    price: 89.99,
    duration: '1 day',
    featured: true,
  },
  {
    title: 'Lucknow Awadhi Cuisine Trail',
    description: 'Royal Mughlai and Awadhi cuisine in the city of Nawabs',
    imageUrl: 'https://images.unsplash.com/photo-1574323347407-f5e1ad6d020b?w=400&h=300&fit=crop',
    destination: 'Lucknow',
    category: 'Food',
    price: 165.00,
    duration: '2 days',
    featured: false,
  },
  {
    title: 'Amritsar Kulcha and Langar',
    description: 'Authentic Punjabi kulchas and community kitchen experience at Golden Temple',
    imageUrl: 'https://images.unsplash.com/photo-1563203369-26f2e4a5ccf7?w=400&h=300&fit=crop',
    destination: 'Amritsar',
    category: 'Food',
    price: 125.00,
    duration: '1 day',
    featured: false,
  },
  {
    title: 'Kolkata Sweet and Snack Tour',
    description: 'Rosogulla, mishti doi, and street snacks in the City of Joy',
    imageUrl: 'https://images.unsplash.com/photo-1578985545062-69928b1d9587?w=400&h=300&fit=crop',
    destination: 'Kolkata',
    category: 'Food',
    price: 95.00,
    duration: '1 day',
    featured: false,
  },
  {
    title: 'Banaras Chaat and Lassi Trail',
    description: 'Sacred city\'s famous chaats and thick lassis by the ghats',
    imageUrl: 'https://images.unsplash.com/photo-1615141982883-c7ad0e69fd62?w=400&h=300&fit=crop',
    destination: 'Varanasi',
    category: 'Food',
    price: 75.00,
    duration: '1 day',
    featured: false,
  },
  {
    title: 'Jodhpur Mirchi Vada Experience',
    description: 'Spicy Rajasthani snacks and traditional dal-baati-churma',
    imageUrl: 'https://images.unsplash.com/photo-1559339352-11d035aa65de?w=400&h=300&fit=crop',
    destination: 'Jodhpur',
    category: 'Food',
    price: 105.00,
    duration: '1 day',
    featured: false,
  },
  {
    title: 'Kochi Spice Market Tour',
    description: 'Aromatic spice markets and traditional Kerala fish curry',
    imageUrl: 'https://images.unsplash.com/photo-1596040033229-a9821ebd058d?w=400&h=300&fit=crop',
    destination: 'Kochi',
    category: 'Food',
    price: 115.00,
    duration: '1 day',
    featured: false,
  },
  {
    title: 'Madurai Temple Food Trail',
    description: 'Traditional Tamil meals and temple prasadam in the temple city',
    imageUrl: 'https://images.unsplash.com/photo-1565299507177-b0ac66763828?w=400&h=300&fit=crop',
    destination: 'Madurai',
    category: 'Food',
    price: 85.00,
    duration: '1 day',
    featured: false,
  },
  {
    title: 'Agra Petha and Mughlai Food',
    description: 'Famous Agra petha sweets and authentic Mughlai cuisine',
    imageUrl: 'https://images.unsplash.com/photo-1597318499820-902de2168885?w=400&h=300&fit=crop',
    destination: 'Agra',
    category: 'Food',
    price: 95.00,
    duration: '1 day',
    featured: false,
  },
  {
    title: 'Indore Street Food Capital',
    description: 'Poha, jalebi, and chaat in India\'s street food capital',
    imageUrl: 'https://images.unsplash.com/photo-1555939594-58d7cb561ad1?w=400&h=300&fit=crop',
    destination: 'Indore',
    category: 'Food',
    price: 65.00,
    duration: '1 day',
    featured: false,
  },
  {
    title: 'Dharamshala Tibetan Momos',
    description: 'Authentic Tibetan cuisine in the Dalai Lama\'s residence',
    imageUrl: 'https://images.unsplash.com/photo-1547036967-23d11aacaee0?w=400&h=300&fit=crop',
    destination: 'Dharamshala',
    category: 'Food',
    price: 85.00,
    duration: '1 day',
    featured: false,
  },
  {
    title: 'Chettinad Spicy Cuisine',
    description: 'Fiery and aromatic Chettinad dishes in Tamil Nadu',
    imageUrl: 'https://images.unsplash.com/photo-1567229569827-fde6edec4344?w=400&h=300&fit=crop',
    destination: 'Tamil Nadu',
    category: 'Food',
    price: 135.00,
    duration: '2 days',
    featured: false,
  },
  {
    title: 'Mangalorean Coastal Cuisine',
    description: 'Fresh seafood and coconut-based dishes on the western coast',
    imageUrl: 'https://images.unsplash.com/photo-1586370434639-0fe43b2d32d6?w=400&h=300&fit=crop',
    destination: 'Mangalore',
    category: 'Food',
    price: 145.00,
    duration: '1 day',
    featured: false,
  },
  {
    title: 'Ahmedabad Gujarati Thali',
    description: 'Unlimited traditional thali with dozens of Gujarati specialties',
    imageUrl: 'https://images.unsplash.com/photo-1585937421612-70a008356fbe?w=400&h=300&fit=crop',
    destination: 'Ahmedabad',
    category: 'Food',
    price: 55.00,
    duration: '1 day',
    featured: false,
  },
];

async function main(): Promise<void> {
  console.log('🌱 Starting seed...');

  // Clear existing data
  await prisma.experience.deleteMany();
  console.log('🧹 Cleared existing experiences');

  // Create new experiences
  for (const experience of seedData) {
    await prisma.experience.create({
      data: experience,
    });
  }

  console.log(`✅ Seeded ${seedData.length} experiences`);
}

main()
  .catch((e) => {
    console.error('❌ Seeding failed:', e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });